# -*- coding: utf-8 -*-
"""index.html = the pristine 24 Aug page + the ordering layer.

original_24aug.html is never edited. It is the only copy of what the owner
already has live at hi.laktentedcamp.com (the Workers API refuses to hand a
script back to an API token), so everything is added by this script instead:

    original_24aug.html
      + order/ui.css   -> before </head>
      + order/ui.html  -> immediately before the page's <script>
      + menu_link.json + order/ui.js -> at the end of the page's own <script>

Appending into the existing <script> rather than adding a new one is what
lets the ordering code see MENU, SETS, LANG, drawMenu and friends: they are
top-level const/let, which are script-scoped and invisible to a second tag.

    python3 build_link.py && python3 build_page.py && python3 build_worker.py
"""
import json, io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
def read(*p): return io.open(os.path.join(HERE, *p), encoding='utf-8').read()

page = read('original_24aug.html')

# Corrections the owner gave on 04 Sep 2026. Applied here rather than by
# editing original_24aug.html, because that file is the only copy of what is
# live at hi.laktentedcamp.com and has to stay byte-identical to it.
#
#   "we do not provide food in room services, we do not have hat in room"
#
# So: drop the in-tent dining offer entirely, and stop promising a hat. Each
# correction is checked below -- if the page wording ever changes and one of
# these stops matching, the build fails instead of quietly shipping a promise
# the camp does not keep.
CORRECTIONS = [
    # the whole <li> offering in-tent dining, in all four languages
    ('<li data-vi="<strong>\u0102n t\u1ea1i l\u1ec1u</strong> ph\u1ee5 thu, g\u1ecdi l\u1ec5 t\u00e2n tr\u01b0\u1edbc 30 ph\u00fat"'
     ' data-fr="<strong>Service en tente</strong> suppl\u00e9ment plateau, commandez 30 min \u00e0 l\'avance"'
     ' data-he="<strong>\u05d4\u05d2\u05e9\u05d4 \u05dc\u05d0\u05d5\u05d4\u05dc</strong> \u05ea\u05d5\u05e1\u05e4\u05ea \u05e7\u05d8\u05e0\u05d4, \u05d9\u05e9 \u05dc\u05d4\u05d6\u05de\u05d9\u05df 30 \u05d3\u05e7\u05d5\u05ea \u05de\u05e8\u05d0\u05e9">'
     '<strong>In-tent dining</strong> small tray charge, order 30 min ahead</li>', ''),
    # no hat is provided
    ('M\u1ed7i ph\u00f2ng \u0111\u1ec1u c\u00f3 \u00f4, \u0111\u00e8n pin v\u00e0 m\u0169',
     'M\u1ed7i ph\u00f2ng \u0111\u1ec1u c\u00f3 \u00f4 v\u00e0 \u0111\u00e8n pin'),
    ('Un parapluie, une lampe torche et un chapeau sont fournis',
     'Un parapluie et une lampe torche sont fournis'),
    ('\u05d1\u05db\u05dc \u05d7\u05d3\u05e8 \u05d9\u05e9 \u05de\u05d8\u05e8\u05d9\u05d9\u05d4, \u05e4\u05e0\u05e1 \u05d5\u05db\u05d5\u05d1\u05e2',
     '\u05d1\u05db\u05dc \u05d7\u05d3\u05e8 \u05d9\u05e9 \u05de\u05d8\u05e8\u05d9\u05d9\u05d4 \u05d5\u05e4\u05e0\u05e1'),
    ('An umbrella, a flashlight and a hat are provided',
     'An umbrella and a flashlight are provided'),
]
for old, new in CORRECTIONS:
    if page.count(old) != 1:
        sys.exit('correction no longer matches the page (%d hits): %s'
                 % (page.count(old), old[:70]))
    page = page.replace(old, new)
print('applied %d owner corrections' % len(CORRECTIONS))
css  = read('order', 'ui.css')
body = read('order', 'ui.html')
js   = read('order', 'ui.js')
link = json.loads(read('menu_link.json'))

for tag in ('</head>', '<script>', '</script>'):
    if page.count(tag) != 1:
        sys.exit('expected exactly one %s in the page, found %d'
                 % (tag, page.count(tag)))

blob = ('\n/* generated by build_link.py -- edit menu_link.py, not this */\n'
        'const LINK = ' + json.dumps(link, ensure_ascii=False) + ';\n')

out = page
out = out.replace('</head>', '<style>\n' + css + '</style>\n</head>')
out = out.replace('</script>', blob + js + '\n</script>')
# The page's <script> is the last element in the body and wires up its own
# handlers as it runs, so the ordering markup has to exist BEFORE it. Putting
# it before </body> instead puts it after the script, and getElementById
# returns null for every control.
out = out.replace('<script>', body + '\n<script>')

io.open(os.path.join(HERE, 'index.html'), 'w', encoding='utf-8').write(out)
print('index.html %d bytes (page %d + ordering %d)'
      % (len(out.encode()), len(page.encode()), len(out.encode()) - len(page.encode())))
items = link['items']
print('linked dishes %d, of which variant groups %d, not sold %d; sets %d'
      % (sum(1 for v in items.values() if not v.get('absent')),
         sum(1 for v in items.values() if v.get('v')),
         sum(1 for v in items.values() if v.get('absent')),
         len(link['sets'])))
